### first Stage ###
FROM node:18.17.1-slim As builder

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build  # Use "npm run build" instead of "npm build"

### Second Stage ###
FROM caddy:2.7.4-alpine

ARG CADDYFILE

COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80
EXPOSE 443
