version: "3"
services:
  react-app:
    image: react-app-dev
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules

  server:
    image: server
    restart: unless-stopped
    env_file: ./server/config/dev.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-app:
    driver: local
