version: "3"
services:
  react-app:
    image: react-app-production-local
    restart: unless-stopped
    ports: 
     - "80:80"
     - "443:443"
    volumes:
     - caddy-data:/data
     - caddy-config:/config
    networks:
     - mern-app

  server:
    image: server
    restart: unless-stopped
    env_file: ./server/config/dev.env
    ports:
     - "5000:5000"
    networks:
      - mern-app
  
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-app:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
